---
galaxy_info:
  role_name: "{{cookiecutter.playbook_name}}"
  author: ""
  description: ""
  company: ""
  issue_tracker_url: ""
  license: "MIT"
  min_ansible_version: "2.5"
  platforms:
    - name: "Ubuntu"
      versions:
        - "bionic"
    - name: "EL"
      versions:
        - "7"

  galaxy_tags: []

dependencies: []
