---
- name: "Load variables based on OS family"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "main.yml"

- name: "Install requirements"
  package:
    name: "{{ requirements }}"
    state: present
  register: status
  retries: 10
  delay: 2
  until: status is success
  become: True
  when: (requirements | default([])) | length > 0

- name: "Choose platform based task"
  include_tasks: "{{ platform }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_facts.system }}.yml"
    - "unsupported.yml"
  loop_control:
    loop_var: platform
